---
# Global settings for both C and C++
Hover:
  ShowAKA: true
InlayHints:
  DeducedTypes: true
  Enabled: true
  ParameterNames: true

---
# C++ Specific Configuration
If:
  PathMatch: [.*\.cpp, .*\.hpp, .*\.cc, .*\.hh]
CompileFlags:
  Add: [-std=c++2b, -Wall, -pedantic, -Wextra]
  Compiler: g++
Diagnostics:
  ClangTidy:
    Add: [abseil-*, bugprone-*, cppcoreguidelines-*, modernize-*, performance-*, readability-*]
    Remove: 
      - bugprone-easily-swappable-parameters
      - modernize-use-trailing-return-type
      # ... add other removals here

---
# C Specific Configuration
If:
  PathMatch: .*\.c
CompileFlags:
  Add: [-std=c2x, -Wall, -Wextra, -pedantic]
  Compiler: gcc
Diagnostics:
  ClangTidy:
    Add: [bugprone-*, readability-*, performance-*]
    Remove: [readability-magic-numbers]
